### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by WhiskyModz** [oobbb/Zygisk-Inject-ImGui#1]
Thanks for fixing the Dobby issue

**Comment by oobbb** [comment]
Not recommended
Zygisk has replaced riru

**Comment by WhiskyModz** [comment]
I guess under Android 8 can't use zygisk

**Comment by oobbb** [comment]
I don't know
The device I use is Android 12

**Comment by WhiskyModz** [comment]
I will try to convert for riru like Perfare's il2cpp dumper

**Comment by oobbb** [comment]
Good luck

**Comment by WhiskyModz** [comment]
Can you add bynamemodding I tried but I faced many problems and couldn't fix it

**Comment by WhiskyModz** [comment]
Hello, I hope you are fine, I was continuing to develop your project. 
As in your Android-Mod-Menu-BNM project, I added the bynamemodding tool to your module project and did everything right. I followed the instructions on Bynamemodding's own github page. I got an error. Can you try adding bnm to your module source?

**Comment by oobbb** [comment]
no
I have tried adding bnm to a module
However, the addition of bnm will cause zygisk to not work

**Comment by WhiskyModz** [comment]
I'm just asking out of curiosity. Why didn't you just add the dobby libs? Wouldn't it be easier by adding the libdobby.a lib?

**Comment by WhiskyModz** [comment]
where can i reach you

**Comment by oobbb** [comment]
> where can i reach you

Github

**Comment by WhiskyModz** [comment]
https://github.com/WhiskyModz/tets
what is the problem in my project
![image](https://user-images.githubusercontent.com/96978959/208167773-c05938f2-4c68-493e-9bcc-73dcbd1eee0a.png)

**Comment by WhiskyModz** [comment]
![Screenshot_20221217-231233](https://user-images.githubusercontent.com/96978959/208264550-fff633ef-a388-44f6-9086-2c117e551c30.pn I've added chams to your project and I'm getting this error do you know the solution or did I do something wrong? You can check the source in my profile.

**Comment by WhiskyModz** [comment]
![Screenshot_20221217-231233](https://user-images.githubusercontent.com/96978959/208264619-71f7b68a-9460-467c-bc2e-f042b22ee93b.png)
added chams to your project and I'm getting this error do you know the solution or did I do something wrong? You can check the source in my profile.

**Comment by WhiskyModz** [comment]
Why not upgrade your project? You can add other modding tools. Or you can add libil2cpp links

**Comment by WhiskyModz** [comment]
@oobbb do you have a telegram or discord where i can reach you

**Comment by oobbb** [comment]
> @oobbb do you have a telegram or discord where i can reach you

I have a telegram account, but I don't know how to add friends

**Comment by WhiskyModz** [comment]
@oobbb write me[https://t.me/WhskyBack](url)
