### ISSUE TITLE
add more

### ISSUE THREAD

**Issue by WhiskyModz** [oobbb/Zygisk-Inject-ImGui#2]
Add kittymemory , utils, etc to your project. Can you add tools like

**Comment by oobbb** [comment]
sure
But I need to wait until I have free time

**Comment by WhiskyModz** [comment]
oh ok bro I hope you have free time because I added it myself and got a lot of errors

**Comment by WhiskyModz** [comment]
![image](https://user-images.githubusercontent.com/96978959/208315291-77516c34-d000-42da-9584-49d18629c1dd.png)





https://github.com/WhiskyModz/test/commit/13a808a25a76a42d17c6fd02ed271681189435cei 




added them to the project and i started getting these errors do you know the reason?

**Comment by WhiskyModz** [comment]
https://github.com/kotori2/riru_unity_example/blob/zygisk/module/src/main/cpp/hook_main.cpp

To use libil2cpp.so should I call it like here?
